# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2, strandedness).
# Units are techinical replicates (e.g. lanes, or resequencing of the same biological sample). If the 
# column "strandedness" is present (optional), value can be empty or has one of these values: none, yes
# or reverse.
units: units.tsv

threads: 32

trimmomatic:
  # skip trimming: false or true
  skip: false
  # the trimming parameter, see manual: http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/TrimmomaticManual_V0.32.pdf
  trimmer: "LEADING:3 TAILING:3 SLIDINGWINDOW:4:15 MINLEN:15"
  adapter: "path/to/adapter.fq:2:30:10"

bowtie2:
  # the bowtie2 index
  index: "path/to/bowtie2/index"
  # extra parameters, see manual: http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml
  extra: ""

filter:
  # parameters
  params: "-m pair -f 0 -s 0 -t 20"
