# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2, strandedness).
# Units are techinical replicates (e.g. lanes, or resequencing of the same biological sample). If the 
# column "strandedness" is present (optional), value can be empty or has one of these values: none, yes
# or reverse.
units: units.tsv

mode: tf # histone or tf, "--broad" option will be enabled in macs2 under histone mode

threads: 32

multiqc:
  params: ""

trimmomatic:
  # skip trimming: false or true
  skip: false
  # the trimming parameter, see manual: http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/TrimmomaticManual_V0.32.pdf
  trimmer: "LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:15"
  pe_adapter: "data/TruSeq3-PE.fa"
  se_adapter: "data/TruSeq3-SE.fa"
  adapter_trimmer: ":2:30:10"

bowtie2:
  # the bowtie2 index
  index: "path/to/bowtie2/human/index"
  # extra parameters, see manual: http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml
  extra: ""

samtools_view:
  # flag used to filter
  pe: "-F 1804 -b"
  se: "-F 1796 -b"

filter:
  skip: true
  # parameters
  pe: "-m pair -f 0 -t 10"
  se: "-m single -f 0 -t 10"

macs2: "--gsize mm -q 0.05"

genomecov: "-bg -pc"

bedGraphToBigWig:
  chrom: "data/Mus_musculus.GRCm38.dna.merge.fa.fai"
  params: ""

bamCompare: "--scaleFactorsMethod SES -bl data/mm10-blacklist.v2.bed"
